### Auth Requests
@baseUrl = http://localhost:3000
@contentType = application/json
@accessToken = {{login.response.body.accessToken}}
@refreshToken = {{login.response.body.refreshToken}}

### Register
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "email": "brianmwangicursor@gmail.com",
  "password": "pass123",
  "fullName": "Brian Mwangi"
}

### Verify Email
POST {{baseUrl}}/auth/verify-email
Content-Type: {{contentType}}

{
  "token": "d027197192e5d67daa98088ffa7ce1b3112edeb4b03e34d3feaea45ab95bdae8"
}

### Resend Verification
POST {{baseUrl}}/auth/resend-verification
Content-Type: {{contentType}}

{
  "email": "brianmwangicursor@gmail.com"
}

### Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "brianmwangicursor@gmail.com",
  "password": "pass123"
}

### Refresh tokens
POST {{baseUrl}}/auth/refresh
Content-Type: {{contentType}}

{
  "refreshToken": "{{refreshToken}}"
}

### Logout
POST {{baseUrl}}/auth/logout
Authorization: Bearer {{accessToken}}

### Forgot Password
POST {{baseUrl}}/auth/forgot-password
Content-Type: {{contentType}}

{
  "email": "brianmwangicursor@gmail.com"
}

### Reset Password
POST {{baseUrl}}/auth/reset-password
Content-Type: {{contentType}}

{
  "email": "user@example.com",
  "otp": "123456",
  "newPassword": "newpass123"
}
